import mongoose from "mongoose";
const productschema=new mongoose.Schema({
    productname:{
        type:String,
        required:true
    },
    productimages:[
        {
            type:String,
            required:true
        }
    ],
    originalprice:{
        type:Number,
        required:true
    },
    sellprice:{
        type:Number,
        required:true
    },
    discount:{
        type:Number,
        required:true,
        default:0
    },
    relatedcategory:{
        type:mongoose.Schema.Types.ObjectId,
        ref:"Category"
    },
    assuredproduct:{
        type:Boolean,
        required:true,
        default:true
    },
    description:{
        type:String,
        required:true
    },
    highlights:[
        {
        type:String,
        required:true
        }
    ],
    launchdate:{
        type:Date,
        required:true,
        default:Date.now()
    },
    attributes:{
        type:Map,
        of:String
    },
    seller:{
        type:mongoose.Schema.Types.ObjectId,
        ref:"User"
    },
    numberofproducts:{
        type:Number,
        required:true,
        default:0
    },
    numberofpurchases:{
        type:Number,
        required:true,
        default:0
    },
    deliverycharge:{
        type:Number,
        required:true,
        default:0
    },
    ratings:[
        {   
            type:mongoose.Schema.Types.ObjectId,
            ref:"Rating"    
        }
    ],
    averageRating:{
        type:Number,
        required:true,
        default:0
    },
    numberofratings:{
        type:Number,
        required:true,
        default:0
    },
})

export default mongoose.models.Product || mongoose.model("Product",productschema);