import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Navbar from './components/Navbar'
import Appcontextcreator from './context/Appcontext'
import {Toaster} from "react-hot-toast"
const inter = Inter({ subsets: ['latin'] })
export const metadata: Metadata = {
  title: 'Ecommerceseller',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
         <Appcontextcreator>
            <Navbar/>
            <main>
              {children}
              <Toaster/>
            </main>
         </Appcontextcreator>
        </body>
    </html>
  )
}
